AWSTemplateFormatVersion: 2010-09-09
Description: Backend application for the Balance mobile app

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  pCategories:
    Type: String
  pEnvironment:
    Type: String
    AllowedValues:
    - dev
    - prod

Resources:

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: balance-api-gateway
      StageName: !Ref pEnvironment
      TracingEnabled: true

  # Lambda function to get categories
  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: src/handlers/get-categories.getCategoriesHandler
      MemorySize: 128
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/categories
            Method: GET
            RestApiId: !Ref ApiGateway
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17' 
        Statement:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/balance/categories'
      - Version: '2012-10-17' 
        Statement:
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/balance-activities'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2020
        Minify: false


  # DynamoDB table to store activity types: {id: "ID", name: "ActivityName", category: "CategoryName"}
  ActivitiesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: balance-activities
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  CatergoriesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /balance/categories
      Type: StringList
      Value: !Ref pCategories
